### ISSUE TITLE
Armor defense stat range

### ISSUE THREAD

**Issue by setsuya** [LartTyler/MHWDB-Docs#1]
Is there any interest in including the range in the defense stat that the armor pieces have? Like the non-upgraded base defense value and the fully upgraded end value of them?

I could really use the info to show the result of the mixed set on my set builder/sharer.

**Comment by LartTyler** [comment]
I'm planning on adding this information soon-ish in a future update, but I haven't been able to find those values online anywhere. I wanna put it in, but it'll take me a bit to find all those values in game and put them into the API.

**Comment by setsuya** [comment]
I've been looking around but couldn't find it either. I'll be on the lookout and mention here if I find something around.

**Comment by LartTyler** [comment]
Awesome, thanks! Once I get a chance to add this feature, I'll post another update in here.

**Comment by CarlosFdez** [comment]
Your best shot is to pull it from a Japanese site. I know http://mhwg.org/ has them. An example is available here http://mhwg.org/ida/1191.html. I'm planning on adding them to my own project eventually from there.

**Comment by CarlosFdez** [comment]
I extracted the data they had to https://github.com/CarlosFdez/MHWorldData/blob/master/data/armors/armor_data.json. Feel free to use it, but unfortunately I give no promises as to its accuracy.

**Comment by LartTyler** [comment]
Upgraded armor defense and augmented defense are now in the API as of [v1.8.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.8.0). Thank you to @CarlosFdez for providing the information, it made this much easier to add!
