### ISSUE TITLE
Attributes Interfaces issues

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#11]
ElementTypes:
"Cannot initialize ElementTypes from invalid String value Ice / 210 Blast"	
Ice / 210 Blast is not part of the types.
PhaiTypes
    case Power = "Power Element Phial"
    case PowerPhai = "Power Phial"
power phial in 2 different variations.

will update if i find more.

**Comment by LartTyler** [comment]
Huh. I actually had no idea that any weapons in the game had two elements on them, so the scraper isn't properly parsing elemental damage values for [Twin Nails](http://mhw-db.com/weapons/342) and [Fire and Ice](http://mhw-db.com/weapons/343). I think those are the only two, but if you find any others let me know.

**Comment by LartTyler** [comment]
This is resolved with [v1.6.1](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.6.1). There are three new possible properties on a weapon's Attributes object: `elementType2`, `elementDamage2`, and `elementHidden2`. For any weapon with dual elements (at the moment, just Twin Nails and Fire and Ice), those fields will be populated with their secondary element information.
