### ISSUE TITLE
Switch Axe wrong types..

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#12]
"Cannot initialize PhaiTypes from invalid String value Poison Phial 420"
"Cannot initialize PhaiTypes from invalid String value Poison Phial 300"

and so on.
I think something got mixed in there.

**Comment by LartTyler** [comment]
That's actually intentional. Please see [the Phial Types](https://github.com/LartTyler/MHWDB-Docs/wiki/Attributes-Object#phial-types) section of the attributes page. Some phial types (specifically, elemental phial types such as poison or para) have a strength associated with them, whereas the normal phial types (like impact or power) do not.

**Comment by RayLuxembourg** [comment]
@LartTyler I am not sure how i can make an enum with dynamic number in the end O_O

**Comment by LartTyler** [comment]
In retrospect, it may not be the best way to structure that. I hadn't really considered how that field would be used. I'm going to plan on splitting that up into two fields, `phialType` (which exists already) and `phialPower`.

**Comment by cheng1994** [comment]
@RayLuxembourg You can use regex to capture the number, something like this: 

`/Phial (\d+)/g`

And based on the data the only phial types that do not have an appended value are Impact, Power, and Element Phials so you can do a conditional statement to check for those phials before running a regex against the attribute.

**Comment by RayLuxembourg** [comment]
@cheng1994 
I am using decodable structs in swift 4.
Currently in order to implement those values i will have to rewrite everything and implement custom constructor to handle dynamic values in that string to set everything correctly.

**Comment by LartTyler** [comment]
@RayLuxembourg Do you really need that field to be an enum? If you're just using it for presentation, could it not just be a plain string?

**Comment by RayLuxembourg** [comment]
@LartTyler I can make it simple string then.
Though types in wiki are miss leading.
