### ISSUE TITLE
Add Skill Name to Skill property

### ISSUE THREAD

**Issue by HumbertoMendes** [LartTyler/MHWDB-Docs#14]
Could you please add the Skill Name when returning the Skill property? I can parse it using the slug, but it would be awesome if the name returned along with the other properties.

**Comment by LartTyler** [comment]
Hmm.. So here's the thing. If I add something like `skillName` to ranks, that column doesn't exist on the skill ranks table in the DB, so it wouldn't be query-able. Which isn't necessarily an issue, but it just means that I need to start marking fields as query-able or not, and it makes things a bit less intuitive for a developer in the future.

Not that this is a great solution, but would it be too much to just query the skill endpoint to get the name? All of the endpoints have very strong caching, so it should resolve pretty quickly.

**Comment by baaronp7** [comment]
Tyler,

Could you just have a "displayName" in the skill property? Having to query
again to get the name is a hassel expecially when dealing with such a large
data set when interacting over each piece of armor. Having to call the
skill endpoint for each instance of a skill in a armor piece adds
exponential amount of calls.

Thanks,
Aaron

**Comment by LartTyler** [comment]
Yep, that was the counterargument I was expecting. I'll add it to my backlog.

**Comment by baaronp7** [comment]
Thanks

**Comment by LartTyler** [comment]
The `skillName` field is now available on skill ranks in [v1.6.3](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.6.3).

**Comment by HumbertoMendes** [comment]
Thank you Tyler.
