### ISSUE TITLE
Missing skills (I think monster skills)

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#15]
https://monsterhunterworld.wiki.fextralife.com/Skills

skills like Anjanath Power,
Diablos Power

if possible add them to separate skills category like , Monster skills

**Comment by LartTyler** [comment]
Yep, you're right, it doesn't look like set skills made it in. I'll start looking into that, thanks!

**Comment by LartTyler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Armor set skills](https://trello.com/c/yYuj2Yx5/1-armor-set-skills)

**Comment by LartTyler** [comment]
@RayLuxembourg Set bonuses are available as of [v1.7.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.7.0). For more info, check out the [`bonus` field](https://github.com/LartTyler/MHWDB-Docs/wiki/Armor-Sets#fields) on `ArmorSet` objects.
