### ISSUE TITLE
Add "craftingMaterials" property to Armors and Charms

### ISSUE THREAD

**Issue by HumbertoMendes** [LartTyler/MHWDB-Docs#16]
Hi Tyler,

Do you have any plans on adding the crafting materials to Armors and Charms just like you did to weapons?

Thank you.

**Comment by LartTyler** [comment]
Yep, material costs for armors and charms is a planned feature, I just didn't have as much time to put into the project this last weekend as I'd hoped I would.

**Comment by LartTyler** [comment]
@HumbertoMendes As of [v1.10.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.10.0), armor now has crafting costs as well!

**Comment by HumbertoMendes** [comment]
Thank you Tyler!
