### ISSUE TITLE
Armor set bonus

### ISSUE THREAD

**Issue by kclay** [LartTyler/MHWDB-Docs#17]
I looked at all endpoints and I didn't run across this. Is there currently anyway to derive the skills that are tied to a set bonus.. ie 2 pieces etc?

**Comment by LartTyler** [comment]
Yep, that's been pointed out in #15. Currently working on it, I hope to have it out sometime in the next few days.

**Comment by kclay** [comment]
O sorry I thought that was something totally different,my apologies.

**Comment by LartTyler** [comment]
No worries!
