### ISSUE TITLE
(Refactor) Armor  Resistance 

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#19]
I would love us to move away slowly from the attributes object to more accurate objects.
Possible we add another object to armor 
armor:{
```
resistance {
    fire:0,
    dragon:0,
 ....
   }
}
```
Instead of relying on attributes objects which is very general It would be nice to implement this type:Resistance object inside armor pieces and if possible , default value of 0 if no value at all.
that way it wont be optional value anymore.
also defense is a must property for armor, therefor it should live inside armor object itself and we can avoid relying on attributes object there as well.

**Comment by LartTyler** [comment]
Yeah, in retrospect the generic `attributes` object was a pretty lazy way to store all that information. I'll add this to the backlog, thanks for the input!

**Comment by LartTyler** [comment]
Armor resistances have been migrated to a dedicated `resistances` field in [v1.8.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.8.0).
