### ISSUE TITLE
Weapon upgrades

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#2]
Is it possible to add possible upgrades for a weapon ?

**Comment by LartTyler** [comment]
That information is currently available on the weapons endpoints. Check out the documentation on the `crafting` field: https://github.com/LartTyler/MHWDB-Docs/wiki/Weapons#crafting. On weapons, `crafting.previous` is the ID of the weapon that upgrades into the weapon, and `crafting.branches` is an array of weapons that the weapon can upgrade into.
