### ISSUE TITLE
Defense property in Weapons

### ISSUE THREAD

**Issue by HumbertoMendes** [LartTyler/MHWDB-Docs#23]
Hi,

Some weapons have defense bonuses (I.E. Barroth Blaster 3), but they are not being listed. Are you planning on adding them as well?

Thanks, and keep up the good work!

**Comment by LartTyler** [comment]
I am now! I'd honestly overlooked them, but it should definitely be in there. I'll get it added to the backlog. Thanks!

**Comment by LartTyler** [comment]
This has been added in [v1.9.1](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.9.1).
