### ISSUE TITLE
Add more information to Decorations

### ISSUE THREAD

**Issue by HumbertoMendes** [LartTyler/MHWDB-Docs#24]
Hi Tyler,

Since you are going to restructure the charms, I was thinking that maybe you could follow the same structure for the Decorations as well.

Something like:

```
{
    "name": "Antidote Jewel 1",
    "rarity": 5,
    "slot": 1,
    "id": 1,
    "slug": "antidote-jewel-1",
    "skills": [
        {
          "skill": 1,
          "level": 1,
          "description": "Reduces the duration of poison by 30%.",
          "id": 1,
          "slug": "poison-resistance-rank-1"
        }
      ]
  ]
}
```

What do you think?

**Comment by HumbertoMendes** [comment]
@cheng1994 Exactly my thoughts. I think having it as an array now may prevent future incompatibilities in the future if (or even when) Capcom adds decorations with multiple skills.

**Comment by LartTyler** [comment]
That's a good point. I'd completely forgotten about multi-skill decorations in previous versions, and I could definitely see that being a thing in World at some point. I'll plan on making it an array, thanks for the input!

**Comment by LartTyler** [comment]
This has been added in [v1.9.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.9.0).
