### ISSUE TITLE
Some GET requests return error

### ISSUE THREAD

**Issue by declanjcurrey** [LartTyler/MHWDB-Docs#29]
Some GET requests don't work. This could be due to missing data but for example:

Trying to get all weapons using https://mhw-db.com/weapons - returns an error.

Searching for a weapon based on its ID also fails on weapons with an ID > 100, for example:

https://mhw-db.com/weapons/179 returns the same error as above.

I'm wondering if this could be fixed because the API when data is returned! Thanks for your work on it!

**Comment by LartTyler** [comment]
I'm seeing this happen too. It definitely shouldn't be. I'm looking into it now, I'll update you once I figure out what's up.

**Comment by LartTyler** [comment]
It looks like mysql had crashed earlier, and failed to restart properly. Everything should be working now!
