### ISSUE TITLE
Missing skill info

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#3]
Name: Agitator
Info : Increases attack power and affinity when large monsters become enraged
LEVEL 1 : 
While active, grants Attack +4 and increases Affinity by 3%

could you add skill info please?

**Comment by LartTyler** [comment]
The Agitator skill is available in the API, please check out [https://mhw-db.com/skills/52](https://mhw-db.com/skills/52). However, it does look like the modifiers didn't get parsed properly, so I'll work on getting those added. Thanks for the heads up!

**Comment by RayLuxembourg** [comment]
@LartTyler Hmm  i mean only the info which is summary of the skill
(Info : Increases attack power and affinity when large monsters become enraged)

**Comment by LartTyler** [comment]
OH! I understand now, my bad. That's definitely something that should have been there from the beginning, but that I never added. Thanks (again) for pointing it out, I'll get to work on it!

**Comment by LartTyler** [comment]
Skill descriptions have been added in [v1.4.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.4.0).
