### ISSUE TITLE
Unable to connect to weapons endpoint

### ISSUE THREAD

**Issue by karisd** [LartTyler/MHWDB-Docs#30]
Hey Tyler,

**First of all, awesome API you built!**

I'm having some issue with your endpoint at https://mhw-db.com/weapons

I am receiving an error: 
Failed to load https://mhw-db.com/weapons: The 'Access-Control-Allow-Origin' header contains the invalid value ''. Origin 'http://localhost:3000' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

But, I am able to retrieve response successfully from https://mhw-db.com/armor

Do you think this is something from my (client) side, or do you need to allow CORS from server?

Let me know,

Thanks!
Karis

**Comment by LartTyler** [comment]
@karisd Glad you're liking the API! All endpoints should have the necessary CORS headers, so you may want to check your client configuration. If you're not able to resolve the issue on your end, feel free to send me the relevant code snippet, and I'll see if I can point you in the right direction.

**Comment by karisd** [comment]
Hey! Still not sure what I'm doing wrong. It's a React app, here is my code. I call this method when loading components to the UI.
```

export function fetchWeapons() {
    return dispatch => {
      dispatch(fetchWeaponsBegin());
      return fetch("https://mhw-db.com/weapons")
        .then(handleErrors)
        .then(res => res.json())
        .then(json => {
          dispatch(fetchWeaponsSuccess(json));
          return json;
        })
        .catch(error => dispatch(fetchWeaponsFailure(error)));
    };
  }
```

The fetch will work with `armor `but doesn't for `weapons`. I'll keep researching, but if anything sticks out to you, let me know.

Thanks!

**Comment by LartTyler** [comment]
Your code looks fine, so just in case, I went and cleared out the Cloudflare cache. I'm wondering if maybe it's just some weirdness with how that endpoint got cached. Make sure you clear your browser's cache before trying again, and please let me know if it continues to happen.

**Comment by karisd** [comment]
@LartTyler Hey, that did the trick. Tried it again before clearing browser cache and it worked. Thanks for your help!!
![image](https://user-images.githubusercontent.com/15019218/41802262-2d1ca994-7645-11e8-8745-94144dd93c4e.png)
