### ISSUE TITLE
SkillRank Modifiers is array or object?

### ISSUE THREAD

**Issue by yoonhok524** [LartTyler/MHWDB-Docs#32]
There is two type of data in SkillRank Modifiers.

Sometimes, it was array.
    - "modifiers": [],

But sometimes it was object.
    - "modifiers": {
                          "health": 15
                      },

Becuase of this difference, parsing is not easy...

**Comment by LartTyler** [comment]
Hmm.. It should definitely be coming back as an object every time. Lemme take a look, and I'll get back to you.

**Comment by LartTyler** [comment]
@yoonhok524 This should be fixed now. Thanks for pointing it out!
