### ISSUE TITLE
Health-modifier is undocumented

### ISSUE THREAD

**Issue by Balothar12** [LartTyler/MHWDB-Docs#35]
Nothing major, but in the list of skill-rank modifiers at https://docs.mhw-db.com/#skillrank-modifiers the "health" modifier doesn't seem to be listed even though it's a valid value for e.g. https://mhw-db.com/skills/17 (or I am blind and can't see it, in which case I apologize).

**Comment by LartTyler** [comment]
Good catch. I'll get it added to the docs, thank you!

**Comment by LartTyler** [comment]
Should be resolved now. I know GitHub Pages likes to cache things pretty heavily, so if you don't see it immediately try clearing your cache.
