### ISSUE TITLE
Issue with Fire and Ice (dual blades)

### ISSUE THREAD

**Issue by bsides** [LartTyler/MHWDB-Docs#37]
Hi! First let me thank you for your work on this api, it’s helping me build a tool.

Now for the bug itself: the weapon ID 343, Fire and Ice, shows only the element Ice in it but its known to have Blast element as well, which isn’t returning in the element array. Am I missing something? I don’t know if it’s happening only with this weapon but I thought reporting would be good to check.

Thanks again

**Comment by LartTyler** [comment]
Hey @bsides!

Nope, it doesn't look like you're missing anything, it's in there incorrectly. I'm aware of several items in the API that are incorrect, and I'm working through getting them fixed. As it stands right now, the API depends on scraped data in order to update, and since so many sources have incorrect or incomplete information, I've been working to move away from the reliance on scraped data. Once that system is out (hopefully in the next week or two), I can fix this issue for you, along with the other issues that have been brought to my attention.

I'll keep you posted! Sorry for the inconvenience.

**Comment by bsides** [comment]
Thanks @LartTyler I really appreciate your quick answer. Regarding the rest of the work, if you need any help let me know. I'm not that good with Ruby but I can try a thing or two.

**Comment by LartTyler** [comment]
The project itself is actually written in PHP. This repository just hosts the documentation, which is generated by a Ruby project named Slate.

If you're interested in contributing, I could also use some Typescript help. The solution to using scrapers was to build a system that would allow anyone to submit changes to the API (kind of like a wiki does), and for that I'll need a UI. I can build the thing, but if you know Typescript and React and would like to lend a hand, I'd be happy to discuss it more.

**Comment by bsides** [comment]
I do know more of PHP but since I don't use it for a long time a lot of things must have changed so I don't think I'll be much of help there. 

But in Typescript I sure can help. I'm a frontend developer and I'm building a tool to make/save build sets in React right now. I understand you need a simple crud and that would be easy to do (and maybe we can get some extra lib to do the hard lifting for us). Let me know if you want it.

**Comment by LartTyler** [comment]
I'm wrapping up the API endpoints to support a contribution system, but I'm pretty close to a working prototype. I don't have any docs typed up for the system yet, so it might be a bit of a pain to write a frontend for, but if you're interested in giving it a shot I'd really appreciate the help.

As an example, working with skills in the contrib system would use the following endpoints. Such endpoints exist for any object in the API that has it's own endpoint (i.e. `/armor` and `/weapons`). There's currently 11 different objects that are supported in the contribution system.

`PUT /contrib/skills`
Creates a new skill in the data repository, to be imported with the next release. Some fields are required, such as `name`, `slug`, and `description` on skills.

`GET /contrib/skills/<id>`
Returns the skill whose ID matches `<id>`. The returned object is the current value as it exists in the data repository, not necessarily how it exists in the API.

`PATCH /contrib/skills/<id>`
Updates the skill whose ID matches `<id>`. The payload of the request should be a JSON object describing which fields to update. Certain fields (such as `ranks` on skills) must be provided in their entirety.

`DELETE /contrib/skills/<id>`
Deletes the skill whose ID matches `<id>`.

If you wanna talk details, I've got a room [set up on Gitter](https://gitter.im/mhw-db/contrib-system) (or if you have Discord or something and would prefer to use that, just shoot an email to tyler@lartonoix.com with your info).

**Comment by LartTyler** [comment]
This has been resolved. ["Fire and Ice"](https://mhw-db.com/weapons/343) now has both elements listed.
