### ISSUE TITLE
Kulve Taroth updated equipment

### ISSUE THREAD

**Issue by muradkh786** [LartTyler/MHWDB-Docs#39]
Is there anything you might need help with, with getting Kulve information into the API?

**Comment by LartTyler** [comment]
If you know any Typescript and would be willing to contribute to the contribution system, any help would be appreciated. At the moment, the API depends on scraping multiple fan sites for data, which is too inconsistent / inaccurate for me to continue using. Once I finish working on updating the API to allow changes without scraping, I'll be able to get the Kulve weapons (and all the other missing event gear) into the API.

**Comment by muradkh786** [comment]
Sure, I'm okay at using JavaScript and I can look into TypeScript. Thanks for the update! I'll see what I can manage this weekend.
