### ISSUE TITLE
$like query can't find Beta armors

### ISSUE THREAD

**Issue by AberrantWolf** [LartTyler/MHWDB-Docs#41]
The following query for Alpha Nergigante armors returns the relevant pieces:
`https://mhw-db.com/armor?q={"name":{"$like":"Nerg%Alpha"}}`

However, changing the "Alpha" to "Beta" returns a formatting error.
`https://mhw-db.com/armor?q={"name":{"$like":"Nerg%Beta"}}`
> `{"error":{"code":"search.malformed_query","message":"Your query object was invalid; check your syntax and try again"}}`
It looks like I can add use "Nerg%B%", which will find the Beta items (though it also returns the vambraces -- so I'm guessing case doesn't matter), but as soon as I add the 'e' ("B" -> "Be"), it tells me the search was malformed.

**Comment by LartTyler** [comment]
Are you properly URL encoding the percent sign? Loading [https://mhw-db.com/armor?q={"name":{"$like":"Nerg%25Beta"}}](https://mhw-db.com/armor?q={"name":{"$like":"Nerg%25Beta"}}) (where the `%` is encoded as `%25`) should work as expected.

**Comment by AberrantWolf** [comment]
That was it. My bad, cheers!
