### ISSUE TITLE
Is it possible to combine query with projection?

### ISSUE THREAD

**Issue by AberrantWolf** [LartTyler/MHWDB-Docs#42]
I can query fine and I can project fine, but I can't figure out how to combine both. I only need a small subset of information at the moment, and I'd rather not require all the extra time to upload/download tons of information my program isn't using. Hopefully it's just some syntax that I'm missing?

And if so, can it go into the docs somewhere (or is it already there and I just missed it)?

**Comment by LartTyler** [comment]
Yes, it is possible to combine both query and projection. If you take a look at the docs for [`GET /weapons` ](https://docs.mhw-db.com/#get-all-weapons) (as an example), you'll see that it lists two GET parameters, `p` and `q`. You can use both at the same time, like so:

[https://mhw-db.com/weapons?q={"type":"charge-blade"}&p={"id":true,"name":true}](https://mhw-db.com/weapons?q={"type":"charge-blade"}&p={"id":true,"name":true})

**Comment by AberrantWolf** [comment]
Ah! It was ampersand! Cheers!
