### ISSUE TITLE
Possible to add rarity to armor sets?

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#5]
Would be nice to display rarity to end user.
<img width="529" alt="screen shot 2018-03-31 at 19 28 48" src="https://user-images.githubusercontent.com/15327989/38165281-c74b31ba-3519-11e8-9a06-ce3dab6ba4bc.png">

**Comment by LartTyler** [comment]
Yep, rarity is another one of those things that I missed, but had intended to add. Thanks for pointing it out!

**Comment by LartTyler** [comment]
Armor rarity is now available as of [v1.5.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.5.0).
