### ISSUE TITLE
Many Missing Ammo Types in Documentation

### ISSUE THREAD

**Issue by DeveloperPaul123** [LartTyler/MHWDB-Docs#58]
The docs for ammo type are missing many types. 

![image](https://user-images.githubusercontent.com/6591180/75119405-9a0ae880-5650-11ea-9ac9-b1cebb221fd3.png)

**Comment by LartTyler** [comment]
@DeveloperPaul123 I'm not so familiar with bowguns, but I'm looking at the ammo types (in the "Ammo Types" section [here](https://monsterhunterworld.wiki.fextralife.com/Heavy+Bowgun)) and everything appears to be included. Do you have a few examples of missing types?

**Comment by DeveloperPaul123** [comment]
Ok apparently I was being really dumb when I first read this and didn't realize column 3 were also separate types. I read each row as a _single_ ammo type 🤦‍♂.

Sorry! Everything seems to be included.
