### ISSUE TITLE
Affinity missing

### ISSUE THREAD

**Issue by cheng1994** [LartTyler/MHWDB-Docs#9]
I noticed that none of the weapons list affinity. It seems that you do label affinity as a possible key in the attributes; however, it looks like no weapons list affinity. For example, Maladay's Kiss 3 json object below doesn't list affinity when it should be 20% affinity. For display it would be cool to have to appear in the data as a decimal but being a whole number is a non issue. 

`
    {
        "id": 30,
        "slug": "maladys-kiss-3",
        "name": "Malady's Kiss 3",
        "type": "great-sword",
        "rarity": 6,
        "attributes": {
            "attack": 768,
            "elementDamage": 450,
            "elementType": "Paralysis",
            "sharpnessRed": 20,
            "sharpnessOrange": 15,
            "sharpnessYellow": 15,
            "sharpnessGreen": 25,
            "sharpnessBlue": 12
        },
    }
`

**Comment by LartTyler** [comment]
Thanks for pointing that out. It definitely should have been there, but I guess I overlooked it.

**Comment by LartTyler** [comment]
This is fixed as of [v1.5.1](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.5.1).
